# Site Settings
title: Croydon's personal website
email: croydondias@gmail.com
description: >
  A guide to getting started with Jekyll.
baseurl: ""
url: "https://croydondias.github.io"
twitter_username: croydondias
github_username:  croydondias
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
